services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - PUID=1234 #CHANGE_TO_YOUR_UID
      - PGID=12345 #CHANGE_TO_YOUR_GID
      - TZ=US/New_York #CHANGE_TO_YOUR_TZ
      - DB_HOST=mariadb-romm
      - DB_NAME=romm
      - DB_ROOT_PASSWORD=DB_ROOT_PASSWORD
      - DB_USER=romm-user
      - DB_PASSWD=DB_PASSWD
      - DB_PORT=3306
      - ROMM_AUTH_SECRET_KEY= # Add your generated key
      - IGDB_CLIENT_ID= # Add your IGDB ID
      - IGDB_CLIENT_SECRET= # Add your IGDB secret
    volumes:
      - /volume1/docker/romm/resources:/romm/resources
      - /volume1/docker/romm/redis-data:/redis-data
      - /volume1/data/media/games/library:/romm/library
      - /volume1/data/media/games/assets:/romm/assets
      - /volume1/data/media/games/config:/romm/config
    ports:
      - 7676:8080/tcp
    network_mode: rommbridge
    depends_on:
      mariadb-romm:
        condition: service_healthy

  mariadb-romm:
    image: mariadb:10.7
    container_name: mariadb-romm
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=MARIADB_ROOT_PASSWORD
      - PUID=1234 #CHANGE_TO_YOUR_UID
      - PGID=12345 #CHANGE_TO_YOUR_GID
      - TZ=US/New_York #CHANGE_TO_YOUR_TZ
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=MARIADB_PASSWORD
    ports:
      - "3309:3306"
    network_mode: rommbridge
    volumes:
      - /volume1/docker/mariadb-romm:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 10s
